/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package eu.clarin.cmdi.vlo.openapi.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import eu.clarin.cmdi.vlo.openapi.client.model.VloRecord;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for VloRecordSearchResult
 */
class VloRecordSearchResultTest {
    private final VloRecordSearchResult model = new VloRecordSearchResult();

    /**
     * Model tests for VloRecordSearchResult
     */
    @Test
    void testVloRecordSearchResult() {
        // TODO: test VloRecordSearchResult
    }

    /**
     * Test the property 'records'
     */
    @Test
    void recordsTest() {
        // TODO: test records
    }

    /**
     * Test the property 'numFound'
     */
    @Test
    void numFoundTest() {
        // TODO: test numFound
    }

    /**
     * Test the property 'start'
     */
    @Test
    void startTest() {
        // TODO: test start
    }

}
