/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package eu.clarin.cmdi.vlo.openapi.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import eu.clarin.cmdi.vlo.openapi.client.model.Resource;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for VloRecord
 */
class VloRecordTest {
    private final VloRecord model = new VloRecord();

    /**
     * Model tests for VloRecord
     */
    @Test
    void testVloRecord() {
        // TODO: test VloRecord
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'dataRoot'
     */
    @Test
    void dataRootTest() {
        // TODO: test dataRoot
    }

    /**
     * Test the property 'sourcePath'
     */
    @Test
    void sourcePathTest() {
        // TODO: test sourcePath
    }

    /**
     * Test the property 'selflink'
     */
    @Test
    void selflinkTest() {
        // TODO: test selflink
    }

    /**
     * Test the property 'profileId'
     */
    @Test
    void profileIdTest() {
        // TODO: test profileId
    }

    /**
     * Test the property 'resources'
     */
    @Test
    void resourcesTest() {
        // TODO: test resources
    }

    /**
     * Test the property 'pathValuesMap'
     */
    @Test
    void pathValuesMapTest() {
        // TODO: test pathValuesMap
    }

    /**
     * Test the property 'fields'
     */
    @Test
    void fieldsTest() {
        // TODO: test fields
    }

}
