/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package eu.clarin.cmdi.vlo.openapi.client.api;

import eu.clarin.cmdi.vlo.openapi.client.model.Facet;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for FacetsApi
 */
@Disabled
public class FacetsApiTest {

    private final FacetsApi api = new FacetsApi();

    
    /**
     * Get the facets and their (top) values and their counts
     *
     * 
     */
    @Test
    public void getFacetTest()  {
        String facetName = null;
        String q = null;
        List<String> fq = null;
        Integer valueCountLimit = null;
        Facet response = api.getFacet(facetName, q, fq, valueCountLimit);

        // TODO: test validations
    }
    
    /**
     * Get the facets and their (top) values and their counts
     *
     * 
     */
    @Test
    public void getFacetsTest()  {
        String q = null;
        List<String> fq = null;
        List<String> fields = null;
        Integer valueCountLimit = null;
        List<Facet> response = api.getFacets(q, fq, fields, valueCountLimit);

        // TODO: test validations
    }
    
}