/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package eu.clarin.cmdi.vlo.openapi.client.api;

import eu.clarin.cmdi.vlo.openapi.client.model.VloRecord;
import eu.clarin.cmdi.vlo.openapi.client.model.VloRecordSearchResult;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for RecordsApi
 */
@Disabled
public class RecordsApiTest {

    private final RecordsApi api = new RecordsApi();

    
    /**
     * Retrieve an individual record by its identifier
     *
     * 
     */
    @Test
    public void getRecordTest()  {
        String id = null;
        VloRecord response = api.getRecord(id);

        // TODO: test validations
    }
    
    /**
     * Retrieve one or more records by query and/or filtered
     *
     * 
     */
    @Test
    public void getRecordsTest()  {
        String q = null;
        List<String> fq = null;
        Integer from = null;
        Integer size = null;
        VloRecordSearchResult response = api.getRecords(q, fq, from, size);

        // TODO: test validations
    }
    
    /**
     * Retrieve the exact number of records that can be retrieved by query and/or filtered as JSON object with a single property &#39;numFound&#39;
     *
     * 
     */
    @Test
    public void getRecordsCountTest()  {
        String query = null;
        List<String> fq = null;
        Map<String, Object> response = api.getRecordsCount(query, fq);

        // TODO: test validations
    }
    
    /**
     * Submit a new record
     *
     * 
     */
    @Test
    public void saveRecordTest()  {
        VloRecord vloRecord = null;
        VloRecord response = api.saveRecord(vloRecord);

        // TODO: test validations
    }
    
}