/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package eu.clarin.cmdi.vlo.openapi.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import eu.clarin.cmdi.vlo.openapi.client.model.VloRecord;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * VloRecordSearchResult
 */
@JsonPropertyOrder({
  VloRecordSearchResult.JSON_PROPERTY_RECORDS,
  VloRecordSearchResult.JSON_PROPERTY_NUM_FOUND,
  VloRecordSearchResult.JSON_PROPERTY_START
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-29T14:32:51.397037+02:00[Europe/Amsterdam]", comments = "Generator version: 7.13.0")
public class VloRecordSearchResult {
  public static final String JSON_PROPERTY_RECORDS = "records";
  @jakarta.annotation.Nullable
  private List<VloRecord> records = new ArrayList<>();

  public static final String JSON_PROPERTY_NUM_FOUND = "numFound";
  @jakarta.annotation.Nullable
  private Long numFound;

  public static final String JSON_PROPERTY_START = "start";
  @jakarta.annotation.Nullable
  private Long start;

  public VloRecordSearchResult() {
  }

  public VloRecordSearchResult records(@jakarta.annotation.Nullable List<VloRecord> records) {
    
    this.records = records;
    return this;
  }

  public VloRecordSearchResult addRecordsItem(VloRecord recordsItem) {
    if (this.records == null) {
      this.records = new ArrayList<>();
    }
    this.records.add(recordsItem);
    return this;
  }

  /**
   * Get records
   * @return records
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RECORDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<VloRecord> getRecords() {
    return records;
  }


  @JsonProperty(JSON_PROPERTY_RECORDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRecords(@jakarta.annotation.Nullable List<VloRecord> records) {
    this.records = records;
  }

  public VloRecordSearchResult numFound(@jakarta.annotation.Nullable Long numFound) {
    
    this.numFound = numFound;
    return this;
  }

  /**
   * Get numFound
   * @return numFound
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NUM_FOUND)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getNumFound() {
    return numFound;
  }


  @JsonProperty(JSON_PROPERTY_NUM_FOUND)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNumFound(@jakarta.annotation.Nullable Long numFound) {
    this.numFound = numFound;
  }

  public VloRecordSearchResult start(@jakarta.annotation.Nullable Long start) {
    
    this.start = start;
    return this;
  }

  /**
   * Get start
   * @return start
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_START)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getStart() {
    return start;
  }


  @JsonProperty(JSON_PROPERTY_START)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStart(@jakarta.annotation.Nullable Long start) {
    this.start = start;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VloRecordSearchResult vloRecordSearchResult = (VloRecordSearchResult) o;
    return Objects.equals(this.records, vloRecordSearchResult.records) &&
        Objects.equals(this.numFound, vloRecordSearchResult.numFound) &&
        Objects.equals(this.start, vloRecordSearchResult.start);
  }

  @Override
  public int hashCode() {
    return Objects.hash(records, numFound, start);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VloRecordSearchResult {\n");
    sb.append("    records: ").append(toIndentedString(records)).append("\n");
    sb.append("    numFound: ").append(toIndentedString(numFound)).append("\n");
    sb.append("    start: ").append(toIndentedString(start)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

