/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package eu.clarin.cmdi.vlo.openapi.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import eu.clarin.cmdi.vlo.openapi.client.model.Resource;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * VloRecord
 */
@JsonPropertyOrder({
  VloRecord.JSON_PROPERTY_ID,
  VloRecord.JSON_PROPERTY_DATA_ROOT,
  VloRecord.JSON_PROPERTY_SOURCE_PATH,
  VloRecord.JSON_PROPERTY_SELFLINK,
  VloRecord.JSON_PROPERTY_PROFILE_ID,
  VloRecord.JSON_PROPERTY_RESOURCES,
  VloRecord.JSON_PROPERTY_LANDING_PAGES,
  VloRecord.JSON_PROPERTY_PATH_VALUES_MAP,
  VloRecord.JSON_PROPERTY_FIELDS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-03T12:14:54.664908+01:00[Europe/Amsterdam]", comments = "Generator version: 7.14.0")
public class VloRecord {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private String id;

  public static final String JSON_PROPERTY_DATA_ROOT = "dataRoot";
  @jakarta.annotation.Nullable
  private String dataRoot;

  public static final String JSON_PROPERTY_SOURCE_PATH = "sourcePath";
  @jakarta.annotation.Nullable
  private String sourcePath;

  public static final String JSON_PROPERTY_SELFLINK = "selflink";
  @jakarta.annotation.Nullable
  private String selflink;

  public static final String JSON_PROPERTY_PROFILE_ID = "profileId";
  @jakarta.annotation.Nullable
  private String profileId;

  public static final String JSON_PROPERTY_RESOURCES = "resources";
  @jakarta.annotation.Nullable
  private List<Resource> resources = new ArrayList<>();

  public static final String JSON_PROPERTY_LANDING_PAGES = "landingPages";
  @jakarta.annotation.Nullable
  private List<Resource> landingPages = new ArrayList<>();

  public static final String JSON_PROPERTY_PATH_VALUES_MAP = "pathValuesMap";
  @jakarta.annotation.Nullable
  private Map<String, List<String>> pathValuesMap = new HashMap<>();

  public static final String JSON_PROPERTY_FIELDS = "fields";
  @jakarta.annotation.Nullable
  private Map<String, List<Object>> fields = new HashMap<>();

  public VloRecord() {
  }

  public VloRecord id(@jakarta.annotation.Nullable String id) {
    
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@jakarta.annotation.Nullable String id) {
    this.id = id;
  }

  public VloRecord dataRoot(@jakarta.annotation.Nullable String dataRoot) {
    
    this.dataRoot = dataRoot;
    return this;
  }

  /**
   * Get dataRoot
   * @return dataRoot
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DATA_ROOT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDataRoot() {
    return dataRoot;
  }


  @JsonProperty(JSON_PROPERTY_DATA_ROOT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDataRoot(@jakarta.annotation.Nullable String dataRoot) {
    this.dataRoot = dataRoot;
  }

  public VloRecord sourcePath(@jakarta.annotation.Nullable String sourcePath) {
    
    this.sourcePath = sourcePath;
    return this;
  }

  /**
   * Get sourcePath
   * @return sourcePath
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SOURCE_PATH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSourcePath() {
    return sourcePath;
  }


  @JsonProperty(JSON_PROPERTY_SOURCE_PATH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSourcePath(@jakarta.annotation.Nullable String sourcePath) {
    this.sourcePath = sourcePath;
  }

  public VloRecord selflink(@jakarta.annotation.Nullable String selflink) {
    
    this.selflink = selflink;
    return this;
  }

  /**
   * Get selflink
   * @return selflink
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SELFLINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSelflink() {
    return selflink;
  }


  @JsonProperty(JSON_PROPERTY_SELFLINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSelflink(@jakarta.annotation.Nullable String selflink) {
    this.selflink = selflink;
  }

  public VloRecord profileId(@jakarta.annotation.Nullable String profileId) {
    
    this.profileId = profileId;
    return this;
  }

  /**
   * Get profileId
   * @return profileId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROFILE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getProfileId() {
    return profileId;
  }


  @JsonProperty(JSON_PROPERTY_PROFILE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProfileId(@jakarta.annotation.Nullable String profileId) {
    this.profileId = profileId;
  }

  public VloRecord resources(@jakarta.annotation.Nullable List<Resource> resources) {
    
    this.resources = resources;
    return this;
  }

  public VloRecord addResourcesItem(Resource resourcesItem) {
    if (this.resources == null) {
      this.resources = new ArrayList<>();
    }
    this.resources.add(resourcesItem);
    return this;
  }

  /**
   * Get resources
   * @return resources
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RESOURCES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Resource> getResources() {
    return resources;
  }


  @JsonProperty(JSON_PROPERTY_RESOURCES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setResources(@jakarta.annotation.Nullable List<Resource> resources) {
    this.resources = resources;
  }

  public VloRecord landingPages(@jakarta.annotation.Nullable List<Resource> landingPages) {
    
    this.landingPages = landingPages;
    return this;
  }

  public VloRecord addLandingPagesItem(Resource landingPagesItem) {
    if (this.landingPages == null) {
      this.landingPages = new ArrayList<>();
    }
    this.landingPages.add(landingPagesItem);
    return this;
  }

  /**
   * Get landingPages
   * @return landingPages
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LANDING_PAGES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Resource> getLandingPages() {
    return landingPages;
  }


  @JsonProperty(JSON_PROPERTY_LANDING_PAGES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLandingPages(@jakarta.annotation.Nullable List<Resource> landingPages) {
    this.landingPages = landingPages;
  }

  public VloRecord pathValuesMap(@jakarta.annotation.Nullable Map<String, List<String>> pathValuesMap) {
    
    this.pathValuesMap = pathValuesMap;
    return this;
  }

  public VloRecord putPathValuesMapItem(String key, List<String> pathValuesMapItem) {
    if (this.pathValuesMap == null) {
      this.pathValuesMap = new HashMap<>();
    }
    this.pathValuesMap.put(key, pathValuesMapItem);
    return this;
  }

  /**
   * Get pathValuesMap
   * @return pathValuesMap
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PATH_VALUES_MAP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, List<String>> getPathValuesMap() {
    return pathValuesMap;
  }


  @JsonProperty(JSON_PROPERTY_PATH_VALUES_MAP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPathValuesMap(@jakarta.annotation.Nullable Map<String, List<String>> pathValuesMap) {
    this.pathValuesMap = pathValuesMap;
  }

  public VloRecord fields(@jakarta.annotation.Nullable Map<String, List<Object>> fields) {
    
    this.fields = fields;
    return this;
  }

  public VloRecord putFieldsItem(String key, List<Object> fieldsItem) {
    if (this.fields == null) {
      this.fields = new HashMap<>();
    }
    this.fields.put(key, fieldsItem);
    return this;
  }

  /**
   * Get fields
   * @return fields
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FIELDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, List<Object>> getFields() {
    return fields;
  }


  @JsonProperty(JSON_PROPERTY_FIELDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFields(@jakarta.annotation.Nullable Map<String, List<Object>> fields) {
    this.fields = fields;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VloRecord vloRecord = (VloRecord) o;
    return Objects.equals(this.id, vloRecord.id) &&
        Objects.equals(this.dataRoot, vloRecord.dataRoot) &&
        Objects.equals(this.sourcePath, vloRecord.sourcePath) &&
        Objects.equals(this.selflink, vloRecord.selflink) &&
        Objects.equals(this.profileId, vloRecord.profileId) &&
        Objects.equals(this.resources, vloRecord.resources) &&
        Objects.equals(this.landingPages, vloRecord.landingPages) &&
        Objects.equals(this.pathValuesMap, vloRecord.pathValuesMap) &&
        Objects.equals(this.fields, vloRecord.fields);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, dataRoot, sourcePath, selflink, profileId, resources, landingPages, pathValuesMap, fields);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VloRecord {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    dataRoot: ").append(toIndentedString(dataRoot)).append("\n");
    sb.append("    sourcePath: ").append(toIndentedString(sourcePath)).append("\n");
    sb.append("    selflink: ").append(toIndentedString(selflink)).append("\n");
    sb.append("    profileId: ").append(toIndentedString(profileId)).append("\n");
    sb.append("    resources: ").append(toIndentedString(resources)).append("\n");
    sb.append("    landingPages: ").append(toIndentedString(landingPages)).append("\n");
    sb.append("    pathValuesMap: ").append(toIndentedString(pathValuesMap)).append("\n");
    sb.append("    fields: ").append(toIndentedString(fields)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

